---
abstract: 'communicates with DPD API'
author:
  - 'Richard Newsham <richard@simperl.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-DPD-API
requires:
  HTTP::Request::Common: 0
  JSON: 0
  LWP::UserAgent: 0
  Moo: 0
  URI::Escape: 0
  namespace::clean: 0
version: v0.0002
